version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
    timezone: Europe/Berlin
  target-branch: "dependencyAutoUpdate"
  open-pull-requests-limit: 20
  assignees:
  - DutchmanNL