version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "03:37"
      timezone: Europe/Berlin
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "04:17"
      timezone: Europe/Berlin
    open-pull-requests-limit: 30
