version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
      time: '04:00'
      timezone: Europe/Berlin
    assignees:
      - DrozmotiX
    versioning-strategy: increase
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
      time: '04:00'
      timezone: Europe/Berlin
    open-pull-requests-limit: 30
    assignees:
      - DrozmotiX
