const test_obj = [
	{
		"Device": "discovergy.0.1024000034.Power_Total",
		"alias": "Device_1",
		"unit": "kWh",
		"days": 7,
		"weeks": 4,
		"quarters": 4,
		"months": 12,
		"years": 1,
		"interval": 3000,
		"cost_calculation": true,
		"meter_history": true,
		"cost_basic": 21,
		"cost_unit": 0.27
	},
	{
		"Device": "discovergy.0.1030002797.Power_Total",
		"alias": "Device_2",
		"unit": "kWh",
		"days": 7,
		"weeks": 4,
		"quarters": 4,
		"months": 12,
		"years": 1,
		"interval": 5000,
		"cost_calculation": true,
		"meter_history": true,
		"cost_basic": 21,
		"cost_unit": 0.27
	},
	{
		"Device": "discovergy.0.1039000655.Power_Total",
		"alias": "Device_3",
		"unit": "kWh",
		"days": 7,
		"weeks": 4,
		"quarters": 4,
		"months": 12,
		"years": 1,
		"interval": 8000,
		"cost_calculation": true,
		"meter_history": true,
		"cost_basic": 21,
		"cost_unit": 0.27
	},
	{
		"Device": "discovergy.0.1124001633.Power_Total",
		"alias": "Device_4",
		"unit": "kWh",
		"days": 7,
		"weeks": 4,
		"quarters": 4,
		"months": 12,
		"years": 1,
		"interval": 3000,
		"cost_calculation": true,
		"meter_history": true,
		"cost_basic": 21,
		"cost_unit": 0.27
	},
	{
		"Device": "discovergy.0.1124001803.Power_Total",
		"alias": "Device_5",
		"unit": "kWh",
		"days": 7,
		"weeks": 4,
		"quarters": 4,
		"months": 12,
		"years": 1,
		"interval": 12000,
		"cost_calculation": true,
		"meter_history": true,
		"cost_basic": 21,
		"cost_unit": 0.27
	},
	{
		"Device": "discovergy.0.1338000808.Power_Total",
		"alias": "Device_6",
		"unit": "kWh",
		"days": 7,
		"weeks": 4,
		"quarters": 4,
		"months": 12,
		"years": 1,
		"interval": 20000,
		"cost_calculation": true,
		"meter_history": true,
		"cost_basic": 21,
		"cost_unit": 0.27
	},
	{
		"Device": "discovergy.0.60708596.Power_Total",
		"alias": "Device_7",
		"unit": "kWh",
		"days": 7,
		"weeks": 4,
		"quarters": 4,
		"months": 12,
		"years": 1,
		"interval": 9000,
		"cost_calculation": true,
		"meter_history": true,
		"cost_basic": 21,
		"cost_unit": 0.27
	},
	{
		"Device": "discovergy.0.35823805.volume",
		"alias": "Device_8",
		"unit": "m3",
		"days": 7,
		"weeks": 4,
		"quarters": 4,
		"months": 12,
		"years": 1,
		"interval": 12000,
		"cost_calculation": true,
		"meter_history": true,
		"cost_basic": 21,
		"cost_unit": 0.27
	}
];
module.exports = test_obj;