const words = {
    days: {
        en: 'days',
        de: 'Tage',
        ru: '????',
        pt: 'dias',
        nl: 'dagen',
        fr: 'journées',
        it: 'giorni',
        es: 'dias',
        pl: 'dni',
    },
    weeks: {
        en: 'weeks',
        de: 'Wochen',
        ru: '??????',
        pt: 'semanas',
        nl: 'weken',
        fr: 'semaines',
        it: 'settimane',
        es: 'semanas',
        pl: 'tygodnie',
    },
    quarters: {
        en: 'quarter',
        de: 'Quartal',
        ru: '????????',
        pt: 'trimestre',
        nl: 'kwartaal',
        fr: 'trimestre',
        it: 'trimestre',
        es: 'trimestre',
        pl: 'jedna czwarta',
    },
    months: {
        en: 'months',
        de: 'Monate',
        ru: '??????',
        pt: 'meses',
        nl: 'maanden',
        fr: 'mois',
        it: 'mesi',
        es: 'meses',
        pl: 'miesi?cy',
    },
    years: {
        en: 'Years',
        de: 'Jahre',
        ru: '???',
        pt: 'Anos',
        nl: 'Jaren',
        fr: 'Années',
        it: 'Anni',
        es: 'Años',
        pl: 'Lata',
    },
    current: {
        en: 'current',
        de: 'aktueller',
        ru: '???',
        pt: 'atual',
        nl: 'huidige',
        fr: 'actuel',
        it: 'attuale',
        es: 'corriente',
        pl: 'obecny',
    },
    Monday: {
        en: 'Monday',
        de: 'Montag',
        ru: '???????????',
        pt: 'Segunda-feira',
        nl: 'maandag',
        fr: 'Lundi',
        it: 'Lunedi',
        es: 'lunes',
        pl: 'poniedzia?ek',
    },
    Tuesday: {
        en: 'Tuesday',
        de: 'Dienstag',
        ru: '???????',
        pt: 'terça',
        nl: 'dinsdag',
        fr: 'Mardi',
        it: 'martedì',
        es: 'martes',
        pl: 'wtorek',
    },
    Wednesday: {
        en: 'Wednesday',
        de: 'Mittwoch',
        ru: '?????',
        pt: 'Quarta-feira',
        nl: 'woensdag',
        fr: 'Mercredi',
        it: 'mercoledì',
        es: 'miércoles',
        pl: '?roda',
    },
    Thursday: {
        en: 'Thursday',
        de: 'Donnerstag',
        ru: '???????',
        pt: 'Quinta-feira',
        nl: 'donderdag',
        fr: 'Jeudi',
        it: 'giovedi',
        es: 'jueves',
        pl: 'czwartek',
    },
    Friday: {
        en: 'Friday',
        de: 'Freitag',
        ru: '???????',
        pt: 'Sexta-feira',
        nl: 'vrijdag',
        fr: 'Vendredi',
        it: 'Venerdì',
        es: 'viernes',
        pl: 'pi?tek',
    },
    Saturday: {
        en: 'Saturday',
        de: 'Samstag',
        ru: '???????',
        pt: 'sábado',
        nl: 'zaterdag',
        fr: 'samedi',
        it: 'Sabato',
        es: 'sábado',
        pl: 'sobota',
    },
    Sunday: {
        en: 'Sunday',
        de: 'Sonntag',
        ru: '???????????',
        pt: 'domingo',
        nl: 'zondag',
        fr: 'dimanche',
        it: 'Domenica',
        es: 'domingo',
        pl: 'niedziela',
    },
    January: {
        en: 'January',
        de: 'Januar',
        ru: '??????',
        pt: 'janeiro',
        nl: 'januari-',
        fr: 'janvier',
        it: 'gennaio',
        es: 'enero',
        pl: 'stycze?',
    },
    February: {
        en: 'February',
        de: 'Februar',
        ru: '???????',
        pt: 'fevereiro',
        nl: 'februari',
        fr: 'février',
        it: 'febbraio',
        es: 'febrero',
        pl: 'luty',
    },
    March: {
        en: 'March',
        de: 'März',
        ru: '????',
        pt: 'Março',
        nl: 'maart',
        fr: 'Mars',
        it: 'marzo',
        es: 'marzo',
        pl: 'Marsz',
    },
    April: {
        en: 'April',
        de: 'April',
        ru: '??????',
        pt: 'abril',
        nl: 'april',
        fr: 'avril',
        it: 'aprile',
        es: 'abril',
        pl: 'kwiecie?',
    },
    May: {
        en: 'May',
        de: 'Kann',
        ru: '???',
        pt: 'Maio',
        nl: 'mei',
        fr: 'Peut',
        it: 'potrebbe',
        es: 'Mayo',
        pl: 'Mo?e',
    },
    June: {
        en: 'June',
        de: 'Juni',
        ru: '????',
        pt: 'Junho',
        nl: 'juni-',
        fr: 'juin',
        it: 'giugno',
        es: 'junio',
        pl: 'czerwiec',
    },
    July: {
        en: 'July',
        de: 'Juli',
        ru: '????',
        pt: 'Julho',
        nl: 'juli-',
        fr: 'juillet',
        it: 'luglio',
        es: 'julio',
        pl: 'lipiec',
    },
    August: {
        en: 'August',
        de: 'August',
        ru: '???????????',
        pt: 'agosto',
        nl: 'augustus',
        fr: 'août',
        it: 'agosto',
        es: 'agosto',
        pl: 'sierpie?',
    },
    September: {
        en: 'September',
        de: 'September',
        ru: '????????',
        pt: 'setembro',
        nl: 'september',
        fr: 'septembre',
        it: 'settembre',
        es: 'septiembre',
        pl: 'wrzesie?',
    },
    October: {
        en: 'October',
        de: 'Oktober',
        ru: '???????',
        pt: 'Outubro',
        nl: 'oktober',
        fr: 'octobre',
        it: 'ottobre',
        es: 'octubre',
        pl: 'pa?dziernik',
    },
    November: {
        en: 'November',
        de: 'November',
        ru: '??????',
        pt: 'novembro',
        nl: 'november',
        fr: 'novembre',
        it: 'novembre',
        es: 'noviembre',
        pl: 'listopad',
    },
    December: {
        en: 'December',
        de: 'Dezember',
        ru: '???????',
        pt: 'dezembro',
        nl: 'december',
        fr: 'décembre',
        it: 'dicembre',
        es: 'diciembre',
        pl: 'grudzie?',
    },
};
module.exports = words;
