/*global systemDictionary:true */
"use strict";

systemDictionary = {
	"Please set time periods here": {
		"en": "Please set time periods here",
		"de": "Bitte stellen Sie hier Zeiträume ein",
		"ru": "Пожалуйста, установите периоды времени здесь",
		"pt": "Por favor, defina períodos de tempo aqui",
		"nl": "Stel hier de tijdsperioden in",
		"fr": "Veuillez définir des périodes ici",
		"it": "Si prega di impostare i periodi di tempo qui",
		"es": "Por favor, establezca períodos de tiempo aquí",
		"pl": "Ustaw tutaj okresy",
		"zh-cn": "请在此处设置时间段"
	  },
	  "Annual overview (recommended)": {
		"en": "Annual overview (recommended)",
		"de": "Jahresübersicht (empfohlen)",
		"ru": "Годовой обзор (рекомендуется)",
		"pt": "Visão geral anual (recomendado)",
		"nl": "Jaaroverzicht (aanbevolen)",
		"fr": "Aperçu annuel (recommandé)",
		"it": "Panoramica annuale (raccomandata)",
		"es": "Resumen anual (recomendado)",
		"pl": "Przegląd roczny (zalecane)",
		"zh-cn": "年度概览（推荐）"
	  },
	  "period of time": {
		"en": "period of time",
		"de": "Zeiträume",
		"ru": "промежуток времени",
		"pt": "período de tempo",
		"nl": "periodes",
		"fr": "période de temps",
		"it": "periodo di tempo",
		"es": "período de tiempo",
		"pl": "okres czasu",
		"zh-cn": "一段的时间"
	  },
	  "number of days": {
		"en": "number of days",
		"de": "Anzahl der Tage",
		"ru": "количество дней",
		"pt": "número de dias",
		"nl": "aantal dagen",
		"fr": "nombre de jours",
		"it": "numero di giorni",
		"es": "número de días",
		"pl": "Liczba dni",
		"zh-cn": "天数"
	  },
	  "Number of weeks": {
		"en": "Number of weeks",
		"de": "Anzahl der Wochen",
		"ru": "Количество недель",
		"pt": "Número de semanas",
		"nl": "Aantal weken",
		"fr": "Nombre de semaines",
		"it": "Numero di settimane",
		"es": "Numero de semanas",
		"pl": "Liczba tygodni",
		"zh-cn": "周数"
	  },
	  "number of months": {
		"en": "number of months",
		"de": "Anzahl der Monate",
		"ru": "количество месяцев",
		"pt": "número de meses",
		"nl": "aantal maanden",
		"fr": "nombre de mois",
		"it": "numero di mesi",
		"es": "número de meses",
		"pl": "liczba miesięcy",
		"zh-cn": "几个月"
	  },
	  "Number of quarters": {
		"en": "Number of quarters",
		"de": "Anzahl der Quartale",
		"ru": "Количество кварталов",
		"pt": "Número de quartos",
		"nl": "Aantal kwartalen",
		"fr": "Nombre de trimestres",
		"it": "Numero di quarti",
		"es": "Número de cuartos",
		"pl": "Liczba kwartałów",
		"zh-cn": "季度数"
	  },
	  "Number of years": {
		"en": "Number of years",
		"de": "Anzahl der Jahre",
		"ru": "Количество лет",
		"pt": "Número de anos",
		"nl": "Aantal jaren",
		"fr": "Nombre d'années",
		"it": "Numero di anni",
		"es": "Número de años",
		"pl": "Liczba lat",
		"zh-cn": "年数"
	  },
	  "Calculation is done every x minutes": {
		"en": "Calculation is done every x minutes",
		"de": "Die Berechnung erfolgt alle x Minuten",
		"ru": "Расчет производится каждые х минут",
		"pt": "O cálculo é feito a cada x minutos",
		"nl": "De berekening wordt elke x minuten uitgevoerd",
		"fr": "Le calcul est fait toutes les x minutes",
		"it": "Il calcolo viene eseguito ogni x minuti",
		"es": "El cálculo se realiza cada x minutos.",
		"pl": "Obliczanie odbywa się co x minut",
		"zh-cn": "每x分钟进行一次计算"
	  },	
	"Advance settings for periode to store": {
		"en": "Advance settings for periode to store",
		"de": "Einstellungen für Zeitraum",
		"ru": "Предварительные настройки для хранения периода",
		"pt": "Configurações avançadas para periode para armazenar",
		"nl": "Voorinstellingen voor de periode die moet worden opgeslagen",
		"fr": "Paramètres avancés pour la période à stocker",
		"it": "Impostazioni avanzate per periodo da memorizzare",
		"es": "Configuraciones avanzadas para periode para almacenar",
		"pl": "Wcześniejsze ustawienia do przechowywania w oknach",
		"zh-cn": "预先存储periode的设置"
	},
	"Advance settings for cost calculation": {
		"en": "Advance settings for cost calculation",
		"de": "Voreinstellungen für die Kostenberechnung",
		"ru": "Расширенные настройки для расчета стоимости",
		"pt": "Configurações avançadas para cálculo de custos",
		"nl": "Voorinstellingen voor kostenberekening",
		"fr": "Paramètres avancés pour le calcul des coûts",
		"it": "Impostazioni avanzate per il calcolo dei costi",
		"es": "Ajustes anticipados para el cálculo de costes.",
		"pl": "Ustawienia zaawansowane do obliczania kosztów",
		"zh-cn": "提前计算成本"
	},
	"hours award": {
		"en": "price per unit",
		"de": "Preis pro Einheit",
		"ru": "цена за единицу",
		"pt": "preço por unidade",
		"nl": "prijs per eenheid",
		"fr": "prix par unité",
		"it": "prezzo per unità",
		"es": "precio por unidad",
		"pl": "Cena za jednostkę",
		"zh-cn": "每单位价格"
	},
	"Electricity": {
		"en": "Electricity",
		"de": "Elektrizität",
		"ru": "Электричество",
		"pt": "Eletricidade",
		"nl": "Elektriciteit",
		"fr": "Électricité",
		"it": "elettricità",
		"es": "Electricidad",
		"pl": "Elektryczność",
		"zh-cn": "电力"
	},
	"Price per unit (€/kWh)": {
		"en": "Price per unit (€/kWh)",
		"de": "Preis pro Einheit (€/kWh)",
		"ru": "Цена за единицу (€/кВтч)",
		"pt": "Preço por unidade (€/kWh)",
		"nl": "Prijs per stuk (€/kWh)",
		"fr": "Prix ​​unitaire (€/kWh)",
		"it": "Prezzo per unità (€/kWh)",
		"es": "Precio por unidad (€/kWh)",
		"pl": "Cena za sztukę (€/kWh)",
		"zh-cn": "单价（€/ kWh）"
	},
	"Price per unit delivery (€/kWh)": {
		"en": "Price per unit delivery (€/kWh)",
		"de": "Preis pro einheit Lieferung (€/kWh)",
		"ru": "Цена за единицу поставки (€/кВтч)",
		"pt": "Preço por entrega unitária (€/kWh)",
		"nl": "Prijs per stuk bezorging (€/kWh)",
		"fr": "Prix ​​unitaire de livraison (€/kWh)",
		"it": "Prezzo per consegna unitaria (€/kWh)",
		"es": "Precio por unidad de entrega (€/kWh)",
		"pl": "Cena za jednostkę dostawy (€/kWh)",
		"zh-cn": "每单位交货价格（欧元/千瓦时）"
	},
	  "Price per unit night current (€/kWh)": {
		"en": "Price per unit night current (€/kWh)",
		"de": "Preis pro Einheit Nachtstrom (€/kWh)",
		"ru": "Цена за единицу ночного тока (€/кВтч)",
		"pt": "Preço por unidade de corrente de noite (€/kWh)",
		"nl": "Prijs per eenheid nachtstroom (€/kWh)",
		"fr": "Prix ​​par unité de nuit actuelle (€/kWh)",
		"it": "Prezzo per unità corrente notturna (€/kWh)",
		"es": "Precio por unidad de corriente nocturna (€/kWh)",
		"pl": "Cena za jednostkę prądu nocnego (€/kWh)",
		"zh-cn": "每单位夜间电流价格（欧元/千瓦时）"
	},
	  "Price per unit (€/m3)": {
		"en": "Price per unit (€/m3)",
		"de": "Preis pro Einheit (€/m3)",
		"ru": "Цена за единицу (€/м3)",
		"pt": "Preço por unidade (€/m3)",
		"nl": "Prijs per stuk (€/m3)",
		"fr": "Prix ​​unitaire (€/m3)",
		"it": "Prezzo per unità (€/m3)",
		"es": "Precio por unidad (€/m3)",
		"pl": "Cena za sztukę (€/m3)",
		"zh-cn": "单价（€/ m3）"
	},
	  "Monthly base price": {
		"en": "Monthly base price",
		"de": "Monatlicher Grundpreis",
		"ru": "Ежемесячная базовая цена",
		"pt": "Preço base mensal",
		"nl": "Maandelijkse basisprijs",
		"fr": "Prix ​​de base mensuel",
		"it": "Prezzo base mensile",
		"es": "Precio base mensual",
		"pl": "Miesięczna cena podstawowa",
		"zh-cn": "每月基价"
	},
	"cost price": {
		"en": "Cost price per month",
		"de": "Kostenpreis pro Monat",
		"ru": "Себестоимость в месяц",
		"pt": "Preço de custo por mês",
		"nl": "Kostprijs per maand",
		"fr": "Prix ​​de revient par mois",
		"it": "Prezzo di costo al mese",
		"es": "Precio de costo por mes",
		"pl": "Koszt za miesiąc",
		"zh-cn": "每月成本价格"
	},
	"calculations": {
		"en": "calculations",
		"de": "Berechnungen",
		"ru": "вычисления",
		"pt": "cálculos",
		"nl": "berekeningen",
		"fr": "calculs",
		"it": "calcoli",
		"es": "cálculos",
		"pl": "obliczenia",
		"zh-cn": "计算"
	},
	"Gas": {
		"en": "Gas",
		"de": "Gas",
		"ru": "газ",
		"pt": "Gás",
		"nl": "Gas",
		"fr": "Gaz",
		"it": "Gas",
		"es": "Gas",
		"pl": "Gaz",
		"zh-cn": "加油站"
		},
		"Water": {
		"en": "Water",
		"de": "Wasser",
		"ru": "вода",
		"pt": "agua",
		"nl": "Water",
		"fr": "Eau",
		"it": "acqua",
		"es": "Agua",
		"pl": "woda",
		"zh-cn": "水"
		},
		"Oil": {
		"en": "Oil",
		"de": "Öl",
		"ru": "масло",
		"pt": "Óleo",
		"nl": "Olie",
		"fr": "Pétrole",
		"it": "Olio",
		"es": "Petróleo",
		"pl": "Olej",
		"zh-cn": "油"
	},
	"Profit per unit (€/kWh)": {
		"en": "Profit per unit (€/kWh)",
		"de": "Gewinn pro Einheit (€/kWh)",
		"ru": "Прибыль за единицу (€/кВтч)",
		"pt": "Lucro por unidade (€/kWh)",
		"nl": "Winst per eenheid (€/kWh)",
		"fr": "Bénéfice par unité (€/kWh)",
		"it": "Profitto per unità (€/kWh)",
		"es": "Beneficio por unidad (€/kWh)",
		"pl": "Zysk na jednostkę (€/kWh)",
		"zh-cn": "每单位利润（欧元/千瓦时）"
	}
};