# Automatically merge Dependabot PRs based on .github/auto-merge.yml

name: Auto-Merge Dependabot PRs

on:
  # WARNING: This needs to be run in the PR base, DO NOT build untrusted code in this action
  # details under https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Auto-merge Dependabot PRs
        uses: iobroker-bot-orga/action-automerge-dependabot@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-file-path: ".github/auto-merge.yml"
          merge-method: "squash"
